set(BUILD_STATIC_LIBRARY ON)
set(BUILD_JAVA_INTERFACE OFF)
set(INSTALL_PYTHON_INTERFACE OFF)
set(BUILD_UTILITIES OFF)
set(BUILD_TESTS OFF)

set(CMAKE_CXX_COMPILER $ENV{OSXCROSS_TARGET_DIR}/bin/x86_64-apple-darwin23-clang++)
set(CMAKE_C_COMPILER $ENV{OSXCROSS_TARGET_DIR}/bin/x86_64-apple-darwin23-clang)
set(CMAKE_OSX_SYSROOT $ENV{OSXCROSS_SDK})
