set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_ARCHITECTURES arm64)

set(CMAKE_OSX_SYSROOT $ENV{OSXCROSS_SDK})

set(VCPKG_C_FLAGS "-I${CMAKE_OSX_SYSROOT}/usr/include")
set(VCPKG_CXX_FLAGS "-I${CMAKE_OSX_SYSROOT}/usr/include -stdlib=libc++")
set(VCPKG_LINKER_FLAGS "-L${CMAKE_OSX_SYSROOT}/usr/lib")

get_filename_component(TOOLCHAIN_FILE "../platform/ioscross/ios.cmake" REALPATH BASE_DIR "${CMAKE_SOURCE_DIR}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${TOOLCHAIN_FILE})
