set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)

get_filename_component(TOOLCHAIN_FILE "../platform/wasm/wasm32.cmake" REALPATH BASE_DIR "${CMAKE_SOURCE_DIR}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${TOOLCHAIN_FILE})
