set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)

get_filename_component(TOOLCHAIN_FILE
    "${CMAKE_CURRENT_LIST_DIR}/../../wasm-emscripten/wasm32.cmake" REALPATH)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${TOOLCHAIN_FILE})
