set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)

set(CMAKE_OSX_SYSROOT $ENV{OSXCROSS_SDK})

set(VCPKG_C_FLAGS "-I${CMAKE_OSX_SYSROOT}/usr/include")
set(VCPKG_CXX_FLAGS "-I${CMAKE_OSX_SYSROOT}/usr/include")
set(VCPKG_LINKER_FLAGS "-L${CMAKE_OSX_SYSROOT}/usr/lib")

get_filename_component(TOOLCHAIN_FILE "../platform/osxcross/osx.cmake" REALPATH BASE_DIR "${CMAKE_SOURCE_DIR}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${TOOLCHAIN_FILE})
