// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef installer_h
#define installer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Output.H>
extern Fl_Output *bintype;
#include <FL/Fl_Check_Button.H>
extern void set_system(Fl_Check_Button*, void*);
extern Fl_Check_Button *systemp;
#include <FL/Fl_File_Input.H>
extern Fl_File_Input *bindir;
extern Fl_File_Input *opcdir;
extern Fl_File_Input *doc;
extern Fl_File_Input *libdir;
extern Fl_File_Input *hdrdir;
extern Fl_File_Input *locdir;
#include <FL/Fl_Progress.H>
extern Fl_Progress *progress;
#include <FL/Fl_Button.H>
extern Fl_Check_Button *doBin;
extern Fl_Check_Button *doOpc;
extern Fl_Check_Button *doDoc;
extern Fl_Check_Button *doLib;
extern Fl_Check_Button *doHdr;
extern Fl_Check_Button *doLoc;
Fl_Double_Window* make_window(char* type);
extern Fl_Output *err_text;
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* make_alert();
extern Fl_Check_Button *do_asound;
extern Fl_Check_Button *do_fluidsynth;
extern Fl_Check_Button *do_jack;
extern Fl_Check_Button *do_lo;
extern Fl_Check_Button *do_portaudio;
extern Fl_Check_Button *do_sndfile;
Fl_Double_Window* make_libraries();
#endif
