// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "installer.h"

Fl_Output *bintype=(Fl_Output *)0;

Fl_Check_Button *systemp=(Fl_Check_Button *)0;

Fl_File_Input *bindir=(Fl_File_Input *)0;

Fl_File_Input *opcdir=(Fl_File_Input *)0;

Fl_File_Input *doc=(Fl_File_Input *)0;

Fl_File_Input *libdir=(Fl_File_Input *)0;

Fl_Light_Button *profile=(Fl_Light_Button *)0;

Fl_Round_Button *shell=(Fl_Round_Button *)0;

Fl_Round_Button *cshell=(Fl_Round_Button *)0;

Fl_Progress *progress=(Fl_Progress *)0;

static void cb_INSTALL(Fl_Button*, void*) {
  do_install = 1;
}

Fl_Double_Window* make_window(char* type) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(370, 325, "Csound5 Installer");
    w = o;
    { Fl_Text_Display* o = new Fl_Text_Display(85, 30, 25, 25, "Csound5 Installer for");
      o->box(FL_NO_BOX);
      o->labelfont(9);
      o->labelsize(20);
    }
    { Fl_Output* o = bintype = new Fl_Output(185, 6, 170, 30);
      o->box(FL_NO_BOX);
      o->labelfont(1);
      o->labelsize(20);
      o->textfont(9);
      o->textsize(20);
    }
    { Fl_Check_Button* o = systemp = new Fl_Check_Button(265, 45, 25, 25, "Install in System Files");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)set_system);
      o->align(FL_ALIGN_LEFT);
    }
    bindir = new Fl_File_Input(90, 75, 235, 30, "Binary");
    opcdir = new Fl_File_Input(90, 115, 235, 30, "Opcodes");
    doc = new Fl_File_Input(90, 155, 235, 30, "Manual");
    libdir = new Fl_File_Input(90, 195, 235, 30, "Libraries");
    { Fl_Group* o = new Fl_Group(90, 240, 235, 65);
      profile = new Fl_Light_Button(90, 245, 115, 40, "Change profile");
      { Fl_Round_Button* o = shell = new Fl_Round_Button(215, 240, 25, 25, "sh/bash");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = cshell = new Fl_Round_Button(215, 265, 40, 25, "csh");
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      o->end();
    }
    progress = new Fl_Progress(90, 290, 235, 15);
    { Fl_Button* o = new Fl_Button(10, 245, 70, 60, "INSTALL");
      o->color((Fl_Color)1);
      o->labelfont(9);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_INSTALL);
    }
    o->end();
  }
  return w;
}

Fl_Output *err_text=(Fl_Output *)0;

static void cb_OK(Fl_Return_Button*, void*) {
  end_alert = 1;
}

Fl_Double_Window* make_alert() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(345, 75, "Installer Alert");
    w = o;
    o->color((Fl_Color)1);
    o->labelcolor(FL_BACKGROUND2_COLOR);
    { Fl_Output* o = err_text = new Fl_Output(5, 10, 310, 25);
      o->color((Fl_Color)1);
      o->textcolor(7);
    }
    { Fl_Return_Button* o = new Fl_Return_Button(5, 45, 50, 25, "OK");
      o->color((Fl_Color)1);
      o->callback((Fl_Callback*)cb_OK);
    }
    o->end();
  }
  return w;
}
