char* SNFDILE_ERRORS[] =
  {
   Str_noop("Format not recognised."),
   Str_noop("System error."),
   Str_noop("Supported file format but file is malformed."),
   Str_noop("Supported file format but unsupported encoding."),
   Str_noop("Error : major format is 0."),
   Str_noop("Error : minor format is 0."),
   Str_noop("File does not exist or is not a regular file (possibly a pipe?)."),
   Str_noop("File exists but no data could be read."),
   Str_noop("Could not open file."),
   Str_noop("Not a valid SNDFILE* pointer."),
   Str_noop("NULL SF_INFO pointer passed to libsndfile."),
   Str_noop("SF_PRIVATE struct incomplete and end of header parsing."),
   Str_noop("Bad FILE pointer."),
   Str_noop("Internal error, Bad pointer."),
   Str_noop("Error : software was misconfigured at compile time (sizeof statbuf.st_size)."),
   Str_noop("Error : Could not file temp dir."),
   Str_noop("Internal malloc () failed."),
   Str_noop("File contains data in an unimplemented format."),
   Str_noop("Attempt to read a non-integer number of channels."),
   Str_noop("Attempt to write a non-integer number of channels."),
   Str_noop("File contains data in an unknown format."),
   Str_noop("Read attempted on file currently open for write."),
   Str_noop("Write attempted on file currently open for read."),
   Str_noop("Error : This file format does not support read/write mode."),
   Str_noop("Internal error : SF_INFO struct incomplete."),
   Str_noop("Error : supplied offset beyond end of file."),
   Str_noop("Error : embedding not supported for this file format."),
   Str_noop("Error : cannot open embedded file read/write."),
   Str_noop("Error : this file format does not support pipe write."),
   Str_noop("Error : bad pointer on SF_VIRTUAL_IO struct."),
   Str_noop("Error : bad coding_history_size in SF_BROADCAST_INFO struct."),
   Str_noop("Error : SF_BROADCAST_INFO struct too large."),
   Str_noop("Error: SF_CART_INFO struct too large."),
   Str_noop("Error: bad tag_text_size in SF_CART_INFO struct."),
   Str_noop("Attempt to write to file with non-interleaved data."),
   Str_noop("Bad karma in seek during interleave read operation."),
   Str_noop("Bad karma in read during interleave read operation."),
   Str_noop("Unspecified internal error."),
   Str_noop("Bad parameter passed to function sf_command."),
   Str_noop("Bad endian-ness. Try default endian-ness"),
   Str_noop("Channel count is zero."),
   Str_noop("Too many channels specified."),
   Str_noop("Bad channel count."),
   Str_noop("Internal psf_fseek() failed."),
   Str_noop("Seek attempted on unseekable file type."),
   Str_noop("Error : combination of file open mode and seek command is ambiguous."),
   Str_noop("Error : invalid seek parameters."),
   Str_noop("Error : parameters OK, but psf_seek() failed."),
   Str_noop("Error : bad mode parameter for file open."),
   Str_noop("Error : attempt to open a pipe in read/write mode."),
   Str_noop("Error on RDWR position (cryptic)."),
   Str_noop("Error : Cannot open file in read/write mode due to string data in header."),
   Str_noop("Error : Command fails because file already has audio data."),
   Str_noop("Error : File type does not support string data."),
   Str_noop("Error : Trying to set a string when file is not in write mode."),
   Str_noop("Error : Maximum string data storage reached."),
   Str_noop("Error : Maximum string data count reached."),
   Str_noop("Error : Bad string data type."),
   Str_noop("Error : file type does not support strings added at end of file."),
   Str_noop("Error : bad string."),
   Str_noop("Error : Weird string error."),
   Str_noop("Error in WAV file. No 'RIFF' chunk marker."),
   Str_noop("Error in WAV file. No 'WAVE' chunk marker."),
   Str_noop("Error in WAV/W64/RF64 file. No 'fmt ' chunk marker."),
   Str_noop("Error in WAV/W64/RF64 file. Malformed 'fmt ' chunk."),
   Str_noop("Error in WAV/W64/RF64 file. Short 'fmt ' chunk."),
   Str_noop("Error in WAV file. 'fact' chunk out of place."),
   Str_noop("Error in WAV file. Bad 'PEAK' chunk."),
   Str_noop("Error in WAV file. 'PEAK' chunk found before 'fmt ' chunk."),
   Str_noop("Error in WAV file. Errors in 'fmt ' chunk."),
   Str_noop("Error in WAV file. Block alignment in 'fmt ' chunk is incorrect."),
   Str_noop("Error in WAV file. No 'data' chunk marker."),
   Str_noop("Error in WAV file. Malformed LIST chunk."),
   Str_noop("Error in WAV file. File contains an unknown chunk marker."),
   Str_noop("Error in WAV file. Data is in WAVPACK format."),
   Str_noop("Error in ADPCM WAV file. Invalid bit width."),
   Str_noop("Error in ADPCM WAV file. Invalid number of channels."),
   Str_noop("Error in ADPCM WAV file. Invalid number of samples per block."),
   Str_noop("Error in GSM610 WAV file. Invalid format chunk."),
   Str_noop("Error in AIFF file, bad 'FORM' marker."),
   Str_noop("Error in AIFF file, 'AIFF' marker without 'FORM'."),
   Str_noop("Error in AIFF file, 'COMM' marker without 'FORM'."),
   Str_noop("Error in AIFF file, 'SSND' marker without 'COMM'."),
   Str_noop("Error in AIFF file, unknown chunk."),
   Str_noop("Error in AIFF file, bad 'COMM' chunk size."),
   Str_noop("Error in AIFF file, bad 'COMM' chunk."),
   Str_noop("Error in AIFF file. 'PEAK' chunk found before 'COMM' chunk."),
   Str_noop("Error in AIFF file. Bad 'PEAK' chunk."),
   Str_noop("Error in AIFF file, bad 'SSND' chunk."),
   Str_noop("Error in AIFF file, no sound data."),
   Str_noop("Error in AIFF file, RDWR only possible if SSND chunk at end of file."),
   Str_noop("Error in AU file, unknown format."),
   Str_noop("Error in AU file, missing '.snd' or 'dns.' marker."),
   Str_noop("Embedded AU file with unknown length."),
   Str_noop("Error while opening RAW file for read. Must specify format and channels.\n"),
   Str_noop("Possibly trying to open unsupported format."),
   Str_noop("Error. RAW file bitwidth must be a multiple of 8."),
   Str_noop("Error. Bad format field in SF_INFO struct when opening a RAW file for read."),
   Str_noop("Error in PAF file, no marker."),
   Str_noop("Error in PAF file, bad version."),
   Str_noop("Error in PAF file, unknown format."),
   Str_noop("Error in PAF file. File shorter than minimal header."),
   Str_noop("Error in PAF file. Bad channel count."),
   Str_noop("Error in 8SVX / 16SV file, no 'FORM' marker."),
   Str_noop("Error in 8SVX / 16SV file, no 'BODY' marker."),
   Str_noop("Error in 8SVX / 16SV file, no sound data."),
   Str_noop("Error in 8SVX / 16SV file, unsupported compression format."),
   Str_noop("Error in 8SVX / 16SV file, NAME chunk too long."),
   Str_noop("Error in NIST file, bad header."),
   Str_noop("Error : NIST file damaged by Windows CR -> CRLF conversion process."),
   Str_noop("Error in NIST file, unsupported compression format."),
   Str_noop("Error in VOC file, no 'Creative Voice File' marker."),
   Str_noop("Error in VOC file, bad format."),
   Str_noop("Error in VOC file, bad version number."),
   Str_noop("Error in VOC file, bad marker in file."),
   Str_noop("Error in VOC file, incompatible VOC sections."),
   Str_noop("Error in VOC file, more than one sample rate defined."),
   Str_noop("Unimplemented VOC file feature, file contains multiple sound sections."),
   Str_noop("Error in VOC file, file contains multiple bit or channel widths."),
   Str_noop("Error in VOC file, too many sections."),
   Str_noop("Error : not able to operate on VOC files over a pipe."),
   Str_noop("Error in IRCAM file, bad IRCAM marker."),
   Str_noop("Error in IRCAM file, bad channel count."),
   Str_noop("Error in IRCAM file, unknown encoding format."),
   Str_noop("Error in W64 file, file contains 64 bit offset."),
   Str_noop("Error in W64 file. No 'riff' chunk marker."),
   Str_noop("Error in W64 file. No 'wave' chunk marker."),
   Str_noop("Error in W64 file. No 'data' chunk marker."),
   Str_noop("Error in ADPCM W64 file. Invalid bit width."),
   Str_noop("Error in ADPCM W64 file. Invalid number of channels."),
   Str_noop("Error in GSM610 W64 file. Invalid format chunk."),
   Str_noop("Error in MAT4 file. No variable name."),
   Str_noop("Error in MAT4 file. No sample rate."),
   Str_noop("Error in MAT5 file. Not able to determine endian-ness."),
   Str_noop("Error in MAT5 file. Bad block structure."),
   Str_noop("Error in MAT5 file. Not able to determine sample rate."),
   Str_noop("Error in PVF file. No PVF1 marker."),
   Str_noop("Error in PVF file. Bad header."),
   Str_noop("Error in PVF file. Bad bit width."),
   Str_noop("Error in XI file. Bad header."),
   Str_noop("Error in XI file. Excess samples in file."),
   Str_noop("Error : not able to operate on XI files over a pipe."),
   Str_noop("Error : not able to operate on HTK files over a pipe."),
   Str_noop("Error : not an SDS file."),
   Str_noop("Error : bad bit width for SDS file."),
   Str_noop("Error : cannot open SD2 file without a file name."),
   Str_noop("Error : bad data offset."),
   Str_noop("Error : bad map offset."),
   Str_noop("Error : bad data length."),
   Str_noop("Error : bad map length."),
   Str_noop("Error : bad resource fork."),
   Str_noop("Error : bad sample size."),
   Str_noop("Error : bad flac header."),
   Str_noop("Error : problem while creating flac decoder."),
   Str_noop("Error : problem with initialization of the flac decoder."),
   Str_noop("Error : flac decoder lost sync."),
   Str_noop("Error : flac does not support this sample rate."),
   Str_noop("Error : flac channel changed mid stream."),
   Str_noop("Error : unknown error in flac decoder."),
   Str_noop("Error : not a WVE file."),
   Str_noop("Error : not able to operate on WVE files over a pipe."),
   Str_noop("Error : Bad bit width for DWVW encoding. Must be 12, 16 or 24."),
   Str_noop("Error : G72x encoding does not support more than 1 channel."),
   Str_noop("Error : Sample rate chosen is known to trigger a Vorbis encoder bug on this CPU."),
   Str_noop("Error : Not an RF64 file."),
   Str_noop("Error in RF64 file. 'PEAK' chunk found before 'fmt ' chunk."),
   Str_noop("Error in RF64 file. No 'data' chunk marker."),
   Str_noop("Error : Failed to open tmp file for ALAC encoding."),
   Str_noop("Error : Bad SF_CHUNK_INFO pointer."),
   Str_noop("Error : Unknown chunk marker."),
   Str_noop("Error : Reading/writing chunks from this file format is not supported."),
   Str_noop("Error : Bad chunk marker."),
   Str_noop("Error : Bad data pointer in SF_CHUNK_INFO struct."),
   Str_noop("Error : Supplied filename too long."),
   Str_noop("Error : Length parameter passed to read/write is negative."),
} ;
