#!/bin/sh
# Refresh every catalog from the messages in the current source tree.
set -eu
cd "$(dirname "$0")/.."

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/csound-po.XXXXXX")
trap 'rm -rf "$tmpdir"' EXIT HUP INT TERM

# Use tracked source files to include new messages and exclude build output.
git ls-files -- '*.c' '*.h' '*.cpp' '*.hpp' '*.cc' '*.cxx' '*.lex' '*.y' '*.m' \
    ':!:tests/**' > "$tmpdir/files"
xgettext --language=C++ --from-code=UTF-8 \
    --keyword --keyword=Str --keyword=Str_noop --keyword=STR \
    --package-name=Csound --package-version=7 \
    --msgid-bugs-address=https://github.com/csound/csound/issues \
    --add-comments=TRANSLATORS --sort-by-file \
    --files-from="$tmpdir/files" --output="$tmpdir/messages.pot"

for catalog in po/*.po; do
    msgmerge --quiet --update --previous --backup=none \
        "$catalog" "$tmpdir/messages.pot"
done
