#!/usr/bin/env python3
"""Generate and check opcode guidance from annotations beside the source."""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "H/opcode_deprecations.def"
REFERENCE = ROOT / "docs/deprecated-opcodes.md"
STRING = r'"(?:\\.|[^"\\])*"'
ENTRY = re.compile(r'^CSOUND_DEPRECATED_OPCODE\(('+STRING+r'), ('+
                   STRING+r'|NULL), (ALIAS|LEGACY|FROZEN), ('+STRING+r')\)$')


def source_text(path):
    """Ignore comments without hiding literals or changing line numbers."""
    comments = re.compile(r'('+STRING+r"|'(?:\\.|[^'\\])*')|/\*.*?\*/|//[^\n]*", re.S)
    return comments.sub(lambda m: m[1] or (" " + "\n" * m[0].count("\n")),
                        path.read_text(errors="replace"))


def source_files():
    for folder in ("Engine", "Opcodes", "InOut", "Top"):
        for path in sorted((ROOT / folder).rglob("*")):
            if path.suffix in (".c", ".cpp", ".h", ".hpp"):
                yield path


def catalog():
    rows = {}
    for path in source_files():
        for number, line in enumerate(source_text(path).splitlines(), 1):
            line = line.strip()
            if not line.startswith("CSOUND_DEPRECATED_OPCODE("):
                continue
            match = ENTRY.fullmatch(line)
            if not match:
                raise ValueError(f"{path}:{number}: invalid descriptor: {line}")
            name, replacement, policy, note = match.groups()
            row = dict(name=json.loads(name),
                       replacement=None if replacement == "NULL" else json.loads(replacement),
                       policy=policy, note=json.loads(note))
            name = row["name"]
            if name in rows and rows[name] != row:
                raise ValueError(f"{path}:{number}: conflicting descriptors for {name}")
            rows[name] = row
    if not rows:
        raise ValueError("No source annotations found")
    return [rows[name] for name in sorted(rows)]


def render_catalog(rows):
    lines = ["/* Generated by scripts/opcode_deprecations.py; do not edit.",
             " * Edit CSOUND_DEPRECATED_OPCODE annotations beside opcode registrations.",
             " * Define CSOUND_OPCODE_DEPRECATION before including this file.",
             " */"]
    for row in rows:
        replacement = "NULL" if row["replacement"] is None else json.dumps(row["replacement"])
        lines.append("CSOUND_OPCODE_DEPRECATION(" + json.dumps(row["name"]) +
                     ", " + replacement + ", " + row["policy"] + ", " +
                     json.dumps(row["note"]) + ")")
    return "\n".join(lines) + "\n"


def registrations():
    """Read static OENTRY initializers, including cast names in C++ plugins."""
    found = []
    for folder in ("Engine", "Opcodes", "InOut", "Top"):
        for path in sorted((ROOT / folder).rglob("*")):
            if path.suffix not in (".c", ".cpp", ".h", ".hpp"):
                continue
            source = source_text(path)
            for match in re.finditer(r'\{\s*(?:\(char\s*\*\)\s*)?"([^"\n]+)"\s*,', source):
                start = match.end()
                depth = 0
                quote = None
                escape = False
                fields = []
                for pos in range(start, len(source)):
                    char = source[pos]
                    if quote:
                        if escape:
                            escape = False
                        elif char == "\\":
                            escape = True
                        elif char == quote:
                            quote = None
                    elif char in "\"'":
                        quote = char
                    elif char in "({[":
                        depth += 1
                    elif char == "}" and depth == 0:
                        fields.append(source[start:pos].strip())
                        break
                    elif char in ")}]":
                        depth -= 1
                    elif char == "," and depth == 0:
                        fields.append(source[start:pos].strip())
                        start = pos + 1
                if len(fields) < 4:
                    continue
                # Outputs and inputs distinguish OENTRY from unrelated arrays.
                if not all(re.fullmatch(r'(?:\(char\s*\*\)\s*)?(?:'+STRING+r'\s*)+', f)
                           for f in fields[2:4]):
                    continue
                status = fields[8] if len(fields) > 8 else ""
                marked = "_QQ" in fields[1] or status in ("1", "2")
                found.append((match[1].split(".")[0], marked, str(path.relative_to(ROOT)), fields[4:7]))
    return found


def validate(rows):
    entries = {row["name"]: row for row in rows}
    source = registrations()
    names = {name for name, _, _, _ in source}
    sources = {path: source_text(ROOT / path) for _, _, path, _ in source}
    errors = []
    for name, marked, path, callbacks in source:
        if marked and name not in entries:
            errors.append(f"{path}: missing descriptor for {name}")
        row = entries.get(name)
        if row is not None:
            text = sources[path]
            if not re.search(r'CSOUND_DEPRECATED_OPCODE\("'+re.escape(name)+r'",', text):
                errors.append(f"{path}: descriptor for {name} must be local to its registration")
        if row is not None and row["policy"] == "FROZEN":
            text = sources[path]
            for callback in callbacks:
                function = re.sub(r'\(SUBR\)|\s', '', callback)
                if function in ("NULL", "0", ""):
                    continue
                pattern = (r'CSOUND_PRESERVE_LEGACY_BEHAVIOR\("'+re.escape(name)+
                           r'"\)\s+(?:static\s+)?(?:int32_t|void)\s+'+
                           re.escape(function)+r'\s*\(')
                if not re.search(pattern, text):
                    errors.append(f"{path}: {function} needs a preserve-legacy marker for {name}")
    for row in rows:
        name, replacement = row["name"], row["replacement"]
        if name not in names:
            errors.append(f"{name}: no static registration found")
        if replacement and replacement not in names:
            errors.append(f"{name}: unknown replacement {replacement}")
        if replacement in entries:
            errors.append(f"{name}: replacement {replacement} is also deprecated")
    if errors:
        raise ValueError("\n".join(sorted(set(errors))))


def render(rows):
    lines = ["<!-- Generated by scripts/opcode_deprecations.py; edit CSOUND_DEPRECATED_OPCODE annotations in opcode source files. -->",
             "# Deprecated opcode catalog", "",
             f"{len(rows)} legacy names and renamed aliases. See [the maintenance policy](opcode-deprecation.md)",
             "before changing historical behavior. Replacements may need different arguments or data.",
             "", "| Opcode | Replacement | Policy | Notes |", "| --- | --- | --- | --- |"]
    for row in rows:
        replacement = f'`{row["replacement"]}`' if row["replacement"] else "No direct replacement documented"
        note = re.sub(r'PR #(\d+)', r'[PR #\1](https://github.com/csound/csound/pull/\1)', row["note"])
        lines.append(f'| `{row["name"]}` | {replacement} | {row["policy"]} | {note.replace("|", "&#124;")} |')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check inventory and generated reference")
    parser.add_argument("--json", action="store_true", help="print machine-readable metadata")
    args = parser.parse_args()
    try:
        rows = catalog()
        validate(rows)
        content = render(rows)
        definitions = render_catalog(rows)
        if args.check:
            if not REFERENCE.exists() or REFERENCE.read_text() != content:
                raise ValueError("Regenerate docs/deprecated-opcodes.md")
            if not CATALOG.exists() or CATALOG.read_text() != definitions:
                raise ValueError("Regenerate H/opcode_deprecations.def")
            print(f"Checked {len(rows)} deprecated opcode names")
        elif args.json:
            print(json.dumps(rows, indent=2))
        else:
            REFERENCE.write_text(content)
            CATALOG.write_text(definitions)
            print(f"Wrote {REFERENCE.relative_to(ROOT)} ({len(rows)} names)")
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
