#!/usr/bin/env python3
"""Render and check the shared Csound opcode deprecation catalog."""
import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "H/opcode_deprecations.def"
REFERENCE = ROOT / "docs/deprecated-opcodes.md"
STRING = r'"(?:\\.|[^"\\])*"'
ENTRY = re.compile(r'^CSOUND_OPCODE_DEPRECATION\(('+STRING+r'), ('+
                   STRING+r'|NULL), (ALIAS|LEGACY|FROZEN), ('+STRING+r')\)$')


def catalog():
    rows = []
    for line in CATALOG.read_text().splitlines():
        if not line.startswith("CSOUND_OPCODE_DEPRECATION("):
            continue
        match = ENTRY.fullmatch(line)
        if not match:
            raise ValueError("Invalid descriptor: " + line)
        name, replacement, policy, note = match.groups()
        rows.append(dict(name=json.loads(name),
                         replacement=None if replacement == "NULL" else json.loads(replacement),
                         policy=policy, note=json.loads(note)))
    names = [row["name"] for row in rows]
    if names != sorted(set(names)):
        raise ValueError("Catalog names must be unique and sorted")
    return rows


def registrations():
    """Read static OENTRY initializers, including cast names in C++ plugins."""
    found = []
    # Preserve string/character literals while removing source comments.
    comments = re.compile(r'('+STRING+r"|'(?:\\.|[^'\\])*')|/\*.*?\*/|//[^\n]*", re.S)
    for folder in ("Engine", "Opcodes", "InOut", "Top"):
        for path in sorted((ROOT / folder).rglob("*")):
            if path.suffix not in (".c", ".cpp", ".h", ".hpp"):
                continue
            source = comments.sub(lambda m: m[1] or "", path.read_text(errors="replace"))
            for match in re.finditer(r'\{\s*(?:\(char\s*\*\)\s*)?"([^"\n]+)"\s*,', source):
                start = match.end()
                depth = 0
                quote = None
                escape = False
                fields = []
                for pos in range(start, len(source)):
                    char = source[pos]
                    if quote:
                        if escape:
                            escape = False
                        elif char == "\\":
                            escape = True
                        elif char == quote:
                            quote = None
                    elif char in "\"'":
                        quote = char
                    elif char in "({[":
                        depth += 1
                    elif char == "}" and depth == 0:
                        fields.append(source[start:pos].strip())
                        break
                    elif char in ")}]":
                        depth -= 1
                    elif char == "," and depth == 0:
                        fields.append(source[start:pos].strip())
                        start = pos + 1
                if len(fields) < 4:
                    continue
                # Outputs and inputs distinguish OENTRY from unrelated arrays.
                if not all(re.fullmatch(r'(?:\(char\s*\*\)\s*)?(?:'+STRING+r'\s*)+', f)
                           for f in fields[2:4]):
                    continue
                status = fields[8] if len(fields) > 8 else ""
                marked = "_QQ" in fields[1] or status in ("1", "2")
                found.append((match[1].split(".")[0], marked, str(path.relative_to(ROOT))))
    return found


def validate(rows):
    entries = {row["name"]: row for row in rows}
    source = registrations()
    names = {name for name, _, _ in source}
    errors = []
    for name, marked, path in source:
        if marked and name not in entries:
            errors.append(f"{path}: missing descriptor for {name}")
    for row in rows:
        name, replacement = row["name"], row["replacement"]
        if name not in names:
            errors.append(f"{name}: no static registration found")
        if replacement and replacement not in names:
            errors.append(f"{name}: unknown replacement {replacement}")
        if replacement in entries:
            errors.append(f"{name}: replacement {replacement} is also deprecated")
    if errors:
        raise ValueError("\n".join(sorted(set(errors))))


def render(rows):
    lines = ["<!-- Generated by scripts/opcode_deprecations.py; edit H/opcode_deprecations.def. -->",
             "# Deprecated opcode catalog", "",
             f"{len(rows)} legacy names and renamed aliases. See [the maintenance policy](opcode-deprecation.md)",
             "before changing historical behavior. Replacements may need different arguments or data.",
             "", "| Opcode | Replacement | Policy | Notes |", "| --- | --- | --- | --- |"]
    for row in rows:
        replacement = f'`{row["replacement"]}`' if row["replacement"] else "No direct replacement documented"
        note = re.sub(r'PR #(\d+)', r'[PR #\1](https://github.com/csound/csound/pull/\1)', row["note"])
        lines.append(f'| `{row["name"]}` | {replacement} | {row["policy"]} | {note.replace("|", "&#124;")} |')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check inventory and generated reference")
    parser.add_argument("--json", action="store_true", help="print machine-readable metadata")
    args = parser.parse_args()
    try:
        rows = catalog()
        validate(rows)
        content = render(rows)
        if args.check:
            if not REFERENCE.exists() or REFERENCE.read_text() != content:
                raise ValueError("Regenerate docs/deprecated-opcodes.md")
            print(f"Checked {len(rows)} deprecated opcode names")
        elif args.json:
            print(json.dumps(rows, indent=2))
        else:
            REFERENCE.write_text(content)
            print(f"Wrote {REFERENCE.relative_to(ROOT)} ({len(rows)} names)")
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
