#define INC_ADSYN
#define INC_ADSYN
#define INC_ARESON
#define INC_ARESON
#define INC_ARESONK
#define INC_ARESONK
#define INC_ASSIGNI
#define INC_ATONE
#define INC_ATONE
#define INC_ATONEK
#define INC_ATONEK
#define INC_ATONEX
#define INC_ATONEX
#define INC_A_K
#define INC_BALANCE
#define INC_BALANCE
#define INC_BALANCE2
#define INC_BALANCE2
#define INC_BUZZ
#define INC_BUZZ
#define INC_DIFF
#define INC_DIFF_K
#define INC_DOWNSAMP
#define INC_EPHASOR
#define INC_EXPSEG
#define INC_EXPSEG_A
#define INC_FOSCIL
#define INC_FOSCIL
#define INC_FOSCILI
#define INC_FOSCILI
#define INC_GAIN
#define INC_GAIN
#define INC_GBUZZ
#define INC_GBUZZ
#define INC_INTEG
#define INC_INTEG_K
#define INC_INTERP
#define INC_LIMIT
#define INC_LIMIT
#define INC_LOSCIL
#define INC_LOSCIL
#define INC_LOSCIL3
#define INC_LOSCIL3
#define INC_LOSCIL3PHS
#define INC_LOSCIL3PS
#define INC_LOSCILPHS
#define INC_LOSCILPHS 
#define INC_LPFORM
#define INC_LPFORM
#define INC_LPFRESON
#define INC_LPFRESON
#define INC_LPINTERP
#define INC_LPINTERP
#define INC_LPREAD
#define INC_LPREAD
#define INC_LPRESON
#define INC_LPRESON
#define INC_LPSLOT
#define INC_LPSLOT
#define INC_OSCIL1
#define INC_OSCILI
#define INC_OSCIL3
#define INC_OSCIL3_a
#define INC_OSCIL3aa
#define INC_OSCIL3ak
#define INC_OSCIL3akA
#define INC_OSCIL3ka
#define INC_OSCIL3kaA
#define INC_OSCIL3kk
#define INC_OSCIL3kkA
#define INC_OSCIL3kkA
#define INC_OSCILI_A
#define INC_OSCILIaa
#define INC_OSCILIaaA
#define INC_OSCILIak
#define INC_OSCILIakA
#define INC_OSCILIka
#define INC_OSCILIkaA
#define INC_OSCILIkk
#define INC_OSCILIkkA
#define INC_OSCILIkkA
#define INC_OSCILIlaA
#define INC_OSCILN
#define INC_OSCIL_a
#define INC_OSCILa
#define INC_OSCILaa
#define INC_OSCILaaA
#define INC_OSCILak
#define INC_OSCILakA
#define INC_OSCILkkA
#define INC_OSCILkkA
#define INC_OSCILkka
#define INC_OSCILkkk
#define INC_OSCILlkaA
#define INC_OSCILka
#define INC_OSCSET
#define INC_OSCSETA
#define INC_OUTS
#define INC_PAN
#define INC_PHASOR
#define INC_PHASOR_K
#define INC_PLUCK
#define INC_PORT
#define INC_PORTK
#define INC_RAND
#define INC_RANDC
#define INC_RANDC_K
#define INC_RANDH
#define INC_RANDH_K
#define INC_RANDI
#define INC_RANDI_K
#define INC_RAND_I
#define INC_RAND_K
#define INC_RESON
#define INC_RESONK
#define INC_RESONX
#define INC_REVERB
#define INC_RMS
#define INC_SAMPHOLD
#define INC_SAMPOLD_K
#define INC_TONE
#define INC_TONEK
#define INC_TONEX
#define INC_UPSAMP
#define INC_UPSAMPLE

#define INC_LINE
#define INC_LINEA
#define INC_EXPON
#define INC_EXPONA
