#define MINTITLE	"all Opcodes"
#define INC_AASSIGN
#define INC_ABS
#define INC_ABS_A
#define INC_ACOS
#define INC_ACOS_A
#define INC_ADSR
#define INC_ADSR_A
#define INC_ADSYN
#define INC_AFTOUCH
#define INC_A_K
#define INC_ALLPOLE
#define INC_ALPASS
#define INC_AMPDB
#define INC_AMPDB_A
#define INC_AMPDBFS
#define INC_AMPDBFS_A
#define INC_AMPMIDI
#define INC_APOLEPARAMS
#define INC_ARESON_AA
#define INC_ARESON_AK
#define INC_ARESON_KA
#define INC_ASIN
#define INC_ASIN_A
#define INC_ASSIGN
#define INC_ATAN
#define INC_ATAN2
#define INC_ATAN2_A
#define INC_ATAN_A
#define INC_ATONEA
#define INC_ATONEX
#define INC_BABO
#define INC_BETARAND
#define INC_BETARAND_A
#define INC_BEXPRAND
#define INC_BEXPRAND_A
#define INC_BIRND
#define INC_BOOLNOT
#define INC_BUTTERBP
#define INC_BUTTERBR
#define INC_BUTTERHP
#define INC_BUTTERLP
#define INC_BUZZ
#define INC_CAUCHYRAND
#define INC_CAUCHYRAND_A
#define INC_CEIL
#define INC_CEIL_A
#define INC_CENT
#define INC_CENT_A
#define INC_CGGOTO
#define INC_CHANCTRL
#define INC_CHANCTRL_I
#define INC_CHANGED_S
#define INC_CIGOTO
#define INC_CINGOTO
#define INC_CKGOTO
#define INC_CNGOTO
#define INC_COMB
#define INC_COMINV
#define INC_COMPILECSD
#define INC_COMPILEORC
#define INC_COMPILESTR
#define INC_CONVAL
#define INC_CONVAL_A
#define INC_COS
#define INC_COS_A
#define INC_COSH
#define INC_COSH_A
#define INC_COSSEG
#define INC_COSSEG_A
#define INC_COSSEGB
#define INC_COSSEGB_A
#define INC_COSSEGR
#define INC_COSSEGR_A
#define INC_CPS
#define INC_CPS2PCH
#define INC_CPSMIDI
#define INC_CPSMIDIB_K
#define INC_CPSMIDINN
#define INC_CPSOCT
#define INC_CPSOCT_A
#define INC_CPSPCH
#define INC_CPSTMID
#define INC_CPSTUN
#define INC_CPSXPCH
#define INC_CTLCHN
#define INC_CTRLINIT
#define INC_CTRLINIT_S
#define INC_CTRLPRINT
#define INC_CTRLPRINTPRESETS
#define INC_CTRLSAVE
#define INC_CTRLSELECT
#define INC_DB
#define INC_DB_A
#define INC_DBAMP
#define INC_DBFSAMP
#define INC_DELAY
#define INC_DELAY1
#define INC_DELAYR
#define INC_DELAYW
#define INC_DELTAP
#define INC_DELTAP3
#define INC_DELTAPN
#define INC_DELTAPX
#define INC_DELTAPXW
#define INC_DELTEIAP
#define INC_DIFF
#define INC_DIFF_K
#define INC_DISKIN
#define INC_DISPFFT
#define INC_DISPFFT_A
#define INC_DISPLAY
#define INC_DISPLAY_A
#define INC_DIV_AA
#define INC_DIVZ
#define INC_DIVZ_AK
#define INC_DIVZ_KA
#define INC_DOWNSAMP
#define INC_DUMPK
#define INC_DUMPK2
#define INC_DUMPK3
#define INC_DUMPK4
#define INC_ENVLPX
#define INC_ENVLPXR
#define INC_ENVLPXR_X
#define INC_ENVLPX_X
#define INC_EPHASOR
#define INC_EVALSTR
#define INC_EVALSTR_K
#define INC_EXP
#define INC_EXP_A
#define INC_EXPON
#define INC_EXPONA
#define INC_EXPRAND
#define INC_EXPRAND_A
#define INC_EXPRANDI
#define INC_EXPRANDI_A
#define INC_EXPSEG
#define INC_EXPSEG_A
#define INC_EXPSEGA
#define INC_EXPSEGB
#define INC_EXPSEGB_A
#define INC_EXPSEGBA
#define INC_EXPSEGR
#define INC_EXPSEGR_A
#define INC_FASSIGN
#define INC_FILEBIT
#define INC_FILEBIT_S
#define INC_FILELEN
#define INC_FILELEN_S
#define INC_FILENCHNLS
#define INC_FILENCHNLS_S
#define INC_FILEPEAK
#define INC_FILESR
#define INC_FILESR_S
#define INC_FILEVALID
#define INC_FILEVALID_S
#define INC_FLOOR
#define INC_FLOOR_A
#define INC_FOSCIL
#define INC_FOSCILI
#define INC_FRAC
#define INC_FRAC_A
#define INC_FTCHNLS
#define INC_FTLEN
#define INC_FTLPTIM
#define INC_FTRESIZE
#define INC_FTSR
#define INC_GAUSSRAND
#define INC_GAUSSRAND_A
#define INC_GAUSSRANS_A
#define INC_GBUZZ
#define INC_GETCFG
#define INC_GOTO
#define INC_HW_CHANNELS
#define INC_IGOTO
#define INC_IHOLD
#define INC_IN
#define INC_IN32
#define INC_INALL
#define INC_INARRAY
#define INC_INCH
#define INC_INCH_M
#define INC_INO
#define INC_INQ
#define INC_INSGLOBAL
#define INC_INSREMOT
#define INC_INT
#define INC_INT_A
#define INC_INTEG
#define INC_INTEG_K
#define INC_INTERP
#define INC_INX
#define INC_INZ
#define INC_KGOTO
#define INC_LFO
#define INC_LINE
#define INC_LINEA
#define INC_LINEN
#define INC_LINENR
#define INC_LINENR_X
#define INC_LINEN_X
#define INC_LINRAND
#define INC_LINRAND_A
#define INC_LINSEG
#define INC_LINSEG_A
#define INC_LINSEGB
#define INC_LINSEGB_A
#define INC_LINSEGR
#define INC_LINSEGR_A
#define INC_LOG
#define INC_LOG10
#define INC_LOG10_A
#define INC_LOG2
#define INC_LOG2_A
#define INC_LOG_A
#define INC_LOGBASE2
#define INC_LOGBASE2_A
#define INC_LOOP_GE
#define INC_LOOP_GE_K
#define INC_LOOP_GT
#define INC_LOOP_GT_K
#define INC_LOOP_LE
#define INC_LOOP_LE_K
#define INC_LOOP_LT
#define INC_LOOP_LT_K
#define INC_LOSCIL
#define INC_LOSCIL3
#define INC_LOSCIL3PHS
#define INC_LOSCILPHS 
#define INC_LPCANAL
#define INC_LPCANAL2
#define INC_LPCFILTER
#define INC_LPFILTER2
#define INC_LPHASOR
#define INC_LPINTERP
#define INC_MADSR
#define INC_MADSR_A
#define INC_MASSIGN_P
#define INC_MASSIG_S
#define INC_MCLOCK
#define INC_MDELAY
#define INC_MIDGLOAL
#define INC_MIDIARP
#define INC_MIDICHN
#define INC_MIDICTRL_I
#define INC_MIDICTRL_K
#define INC_MIDIIN
#define INC_MIDION
#define INC_MIDION2
#define INC_MIDIOUT
#define INC_MIDREMOT
#define INC_MINIT
#define INC_MINIT_A
#define INC_MIRROR
#define INC_MIRROR_A
#define INC_MONITOR
#define INC_MOSCIL
#define INC_MRTMSG
#define INC_MULTITAP
#define INC_MXADSR
#define INC_MXADSR_A
#define INC_NKGOTO
#define INC_NOTEON
#define INC_NOTEONDUR
#define INC_NOTEONDUR2
#define INC_NOTNUM
#define INC_NRPN
#define INC_NSAMP
#define INC_NTRPOL_A
#define INC_NTRPOL_I
#define INC_NTRPOL_K
#define INC_OCTAVE
#define INC_OCTCPS
#define INC_OCTMIDI
#define INC_OCTMIDIB
#define INC_OCTMIDIB_I
#define INC_OCTMIDINN
#define INC_OCTPCH
#define INC_OSCIL1
#define INC_OSCIL1I
#define INC_OSCIL3
#define INC_OSCIL3_a
#define INC_OSCIL3aa
#define INC_OSCIL3ak
#define INC_OSCIL3akA
#define INC_OSCIL3ka
#define INC_OSCIL3kaA
#define INC_OSCIL3kk
#define INC_OSCIL3kkA
#define INC_OSCILa
#define INC_OSCILaa
#define INC_OSCILaaA
#define INC_OSCILak
#define INC_OSCILakA
#define INC_OSCILIaa
#define INC_OSCILIaaA
#define INC_OSCILIak
#define INC_OSCILIakA
#define INC_OSCILIka  
#define INC_OSCILIkaA
#define INC_OSCILIkk
#define INC_OSCILIkkA
#define INC_OSCILIkkAbbbbb
#define INC_OSCILIkki
#define INC_OSCILka
#define INC_OSCILkka
#define INC_OSCILkkA
#define INC_OSCILkkk
#define INC_OSCILlkaA
#define INC_OSCILN
#define INC_OSCILS
#define INC_OUT
#define INC_OUT3
#define INC_OUT4
#define INC_OUTALL
#define INC_OUT_ARRAY
#define INC_OUTAT
#define INC_OUTC
#define INC_OUTC14
#define INC_OUTCH
#define INC_OUTIC
#define INC_OUTPAT
#define INC_OUTPB
#define INC_OUTPC
#define INC_OUTRG
#define INC_OUTS1
#define INC_OUTS2
#define INC_OUTZ
#define INC_PAN
#define INC_PCAUCHYRAND
#define INC_PCAUCHYRAND_A
#define INC_PCHBEND
#define INC_PCHBEND_I
#define INC_PCHMIDI
#define INC_PCHMIDIB_I
#define INC_PCHMIDIB_K
#define INC_PCHMIDINN
#define INC_PCHOCT
#define INC_PEAK
#define INC_PEAKA
#define INC_PGMASSIGN
#define INC_PGMCHN
#define INC_PHASOR
#define INC_PHASOR_K
#define INC_PLUCK
#define INC_POCTVE_A
#define INC_POISONRAND
#define INC_POISSONRAND_A
#define INC_POLYAFT_I
#define INC_POLYAFT_K
#define INC_POW
#define INC_POW_A
#define INC_PRINT
#define INC_PRINTF
#define INC_PRINTK
#define INC_PRINTK2
#define INC_PRINTKS
#define INC_PRINTKS2
#define INC_PRINTKS_S
#define INC_PRINTS
#define INC_PRINTS_S
#define INC_PRINT_TYPE
#define INC_PUTS
#define INC_PVSADSYN  
#define INC_PVSANAL
#define INC_PVSCFS
#define INC_PVSCROSS
#define INC_PVSDISP
#define INC_PVSFREAD
#define INC_PVSFTR
#define INC_PVSFTW
#define INC_PVSINFO
#define INC_PVSLPC
#define INC_PVSMASKA
#define INC_PVSYNTH
#define INC_QINF
#define INC_QINF_A
#define INC_QNAN
#define INC_QNAN_A
#define INC_RAND
#define INC_RANDC
#define INC_RANDC_K
#define INC_RANDH
#define INC_RANDH_K
#define INC_RANDI
#define INC_RANDI_K
#define INC_RAND_K
#define INC_RASSIGN
#define INC_READK
#define INC_READK2
#define INC_READK3
#define INC_READK4
#define INC_READKS
#define INC_READSCORE
#define INC_REINIT
#define INC_RELEASE
#define INC_REMOTEPORT
#define INC_RESONBNK
#define INC_RETURN
#define INC_REVERB
#define INC_REVERB2
#define INC_RIGOTO
#define INC_RND
#define INC_RNDSEED
#define INC_ROUND
#define INC_ROUND_A
#define INC_RTCLOCK
#define INC_S
#define INC_SAMPHOLD
#define INC_SAMPHOLD_K
#define INC_SCHEDKWHEN
#define INC_SCHEDKWHEN_S
#define INC_SCHEDULE
#define INC_SCHEDULE_ARRAY
#define INC_SCHEDULE_N
#define INC_SCHEDULE_S
#define INC_SCHEDULE_SN
#define INC_SCHEDULE_SN  
#define INC_SCHEEDWHEN
#define INC_SEED
#define INC_SEMITONE
#define INC_SEMITONE_A
#define INC_SETKSMPS
#define INC_SIGNUM
#define INC_SIN
#define INC_SIN_A
#define INC_SINH
#define INC_SINH_A
#define INC_SOUNDOUT
#define INC_SPRINTF
#define INC_SQRT
#define INC_SQRT_A
#define INC_STRCAT
#define INC_STRCHAR
#define INC_STRCMP
#define INC_STRCPY
#define INC_STRGET
#define INC_STRLEN
#define INC_STRSET
#define INC_STRSUB
#define INC_STRTOD
#define INC_STRTOL
#define INC_TABLE3_A
#define INC_TABLE3_I
#define INC_TABLE3_K
#define INC_TABLE3KT
#define INC_TABLE3KT_A
#define INC_TABLE_A
#define INC_TABLECOPY
#define INC_TABLE_I
#define INC_TABLEIEKT_A
#define INC_TABLEIGPW
#define INC_TABLEI_I
#define INC_TABLEI_K
#define INC_TABLEIKT
#define INC_TABLE_K
#define INC_TABLEKT
#define INC_TABLEKT_A
#define INC_TABLEMIX
#define INC_TABLENG
#define INC_TABLERA
#define INC_TABLEW
#define INC_TABLEWA
#define INC_TABLEW_AA
#define INC_TABLEW_KK
#define INC_TABLEWKT_A
#define INC_TABLEWKT_K
#define INC_TABLEXKT
#define INC_TALBEI_A
#define INC_TAN
#define INC_TAN_A
#define INC_TANH
#define INC_TANH_A
#define INC_TEMPEST
#define INC_TEMPO
#define INC_TIGOTOb
#define INC_TIMEINSTK
#define INC_TIMEINSTS
#define INC_TIMEK
#define INC_TIMESR
#define INC_TIMOUT
#define INC_TIVAL
#define INC_TONE
#define INC_TONEX
#define INC_TRIGGER
#define INC_TRIGSEQ
#define INC_TRIRAND
#define INC_TRIRAND_A
#define INC_TURNOFF
#define INC_TURNOFF2
#define INC_TURNOFF3
#define INC_TURNON
#define INC_TURNON_S
#define INC_UNIRAND
#define INC_UNIRAND_A
#define INC_UPSAMP
#define INC_VDELAY
#define INC_VDELAY3
#define INC_VDELAYX
#define INC_VDELAYXQ
#define INC_VDELAYXS
#define INC_VDELAYXW
#define INC_VDELAYXWS
#define INC_VELOC
#define INC_WEIBILLRAND
#define INC_WEIBULLRAND_A
#define INC_WRAP
#define INC_WRAP_A
#define INC_XADSR
#define INC_XADSR_A
#define INC_XTRATIM
