b#define MINTITLE	"Nothing excluded"
#define INC_AASIGN
#define INC_ABS
#define INC_ABS_A
#define INC_ACOS
#define INC_ACOS_A
#define INC_ADSR
#define INC_ADSR_A
#define INC_ADSYN
#define INC_ADSYN
#define INC_AMPD
#define INC_AMPDBFS_A
#define INC_AMPDBFS_A
#define INC_ARESON
#define INC_ARESON
#define INC_ARESONK
#define INC_ARESONK
#define INC_ASIN
#define INC_ASIN_A
#define INC_ASSIGN
#define INC_ASSIGNI
#define INC_ATAM2_A
#define INC_ATAN
#define INC_ATAN2
#define INC_ATAN_A
#define INC_ATONE
#define INC_ATONE
#define INC_ATONEK
#define INC_ATONEK
#define INC_ATONEX
#define INC_ATONEX
#define INC_A_K
#define INC_BALANCE
#define INC_BALANCE
#define INC_BALANCE2
#define INC_BALANCE2
#define INC_BIRND
#define INC_BOOLNOT
#define INC_BUZZ
#define INC_CEIL
#define INC_CEIL_A
#define INC_CONVAL
#define INC_CONVAL_A
#define INC_COSH
#define INC_COSH_A
#define INC_COSSEG
#define INC_COSSEGB
#define INC_COSSEGB_A
#define INC_COSSEGR
#define INC_COSSEG_A
#define INC_COSSEG_A
#define INC_CPSMIDI
#define INC_CPSMIDINN
#define INC_CPSOCT
#define INC_CPSOCT_A
#define INC_CPSPCH
#define INC_CPSTMID
#define INC_CPSTUN
#define INC_CPSTUNI
#define INC_CTRLINIT
#define INC_CTRLINIT_S
#define INC_DBAMP
#define INC_DBFSAMP
#define INC_DIFF
#define INC_DIFF_K
#define INC_DOWNSAMP
#define INC_ENVLPX
#define INC_ENVLPXR
#define INC_ENVLPXR_X
#define INC_ENVLPX_X
#define INC_EPHASOR
#define INC_EXP
#define INC_EXPON
#define INC_EXPONA
#define INC_EXPRANDI
#define INC_EXPRANDI_A
#define INC_EXPSEG
#define INC_EXPSEG
#define INC_EXPSEGA
#define INC_EXPSEGB
#define INC_EXPSEGBA
#define INC_EXPSEGB_A
#define INC_EXPSEGR
#define INC_EXPSEGR_A
#define INC_EXPSEG_A
#define INC_EXPSEG_A
#define INC_EXP_A
#define INC_FLOOR
#define INC_FLOOR_A
#define INC_FOSCIL
#define INC_FOSCIL
#define INC_FOSCILI
#define INC_FOSCILI
#define INC_FPLPTIM
#define INC_FRAC
#define INC_FRAC_A
#define INC_FTCHNLS
#define INC_FTCPS
#define INC_FTLEN
#define INC_GAIN
#define INC_GAIN
#define INC_GBUZZ
#define INC_GETSEED
#define INC_IN
#define INC_IN32
#define INC_INALL
#define INC_INARRAY
#define INC_INCH
#define INC_INCH_M
#define INC_INC_DIVZ
#define INC_INC_DIVZ_AA
#define INC_INC_DIVZ_KA
#define INC_INH
#define INC_INO
#define INC_INQ
#define INC_INS
#define INC_INT
#define INC_INTEG
#define INC_INTEG_K
#define INC_INTERP
#define INC_INT_A
#define INC_INX
#define INC_IbbNC_DIVZ_AK
#define INC_LIMIT
#define INC_LIMIT
#define INC_LINE
#define INC_LINEA
#define INC_LINEN
#define INC_LINENR
#define INC_LINENR_X
#define INC_LINEN_X
#define INC_LINRAND
#define INC_LINRAND_A
#define INC_LINSEG
#define INC_LINSEGB
#define INC_LINSEGB_A
#define INC_LINSEGR
#define INC_LINSEGR_A
#define INC_LINSEG_A
#define INC_LOG
#define INC_LOG10
#define INC_LOG10_A
#define INC_LOG2
#define INC_LOG2_A
#define INC_LOG_A
#define INC_LOSCIL
#define INC_LOSCIL
#define INC_LOSCIL3
#define INC_LOSCIL3
#define INC_LOSCIL3PHS
#define INC_LOSCIL3PS
#define INC_LOSCILPHS
#define INC_LOSCILPHS 
#define INC_LPFORM
#define INC_LPFORM
#define INC_LPFRESON
#define INC_LPFRESON
#define INC_LPINTERP
#define INC_LPINTERP
#define INC_LPREAD
#define INC_LPREAD
#define INC_LPRESON
#define INC_LPRESON
#define INC_LPSLOT
#define INC_LPSLOT
#define INC_MADSR
#define INC_MADSR_A
#define INC_MADSR_A
#define INC_MASSIGN_IS
#define INC_MASSIGN_P
#define INC_MAXADSR
#define INC_MINIT
#define INC_MINIT_A
#define INC_MONITOR
#define INC_MXADSR
#define INC_MXADSR_A
#define INC_NOTNUM
#define INC_NSAMP
#define INC_OCTCPS
#define INC_OCTMIDI
#define INC_OCTMIDIB
#define INC_OCTMIDIB_I
#define INC_OCTMIDINN
#define INC_OCTPCH
#define INC_OSCIL1
#define INC_OSCIL3
#define INC_OSCIL3_a
#define INC_OSCIL3aa
#define INC_OSCIL3ak
#define INC_OSCIL3akA
#define INC_OSCIL3ka
#define INC_OSCIL3kaA
#define INC_OSCIL3kk
#define INC_OSCIL3kkA
#define INC_OSCIL3kkA
#define INC_OSCILI
#define INC_OSCILI_A
#define INC_OSCILIaa
#define INC_OSCILIaaA
#define INC_OSCILIak
#define INC_OSCILIakA
#define INC_OSCILIka
#define INC_OSCILIkaA
#define INC_OSCILIkk
#define INC_OSCILIkkA
#define INC_OSCILIkkA
#define INC_OSCILIlaA
#define INC_OSCILN
#define INC_OSCIL_a
#define INC_OSCILa
#define INC_OSCILaa
#define INC_OSCILaaA
#define INC_OSCILak
#define INC_OSCILakA
#define INC_OSCILka
#define INC_OSCILkkA
#define INC_OSCILkkA
#define INC_OSCILkka
#define INC_OSCILkkk
#define INC_OSCILlkaA
#define INC_OSCSET
#define INC_OSCSETA
#define INC_OUT
#define INC_OUTALL
#define INC_OUTC
#define INC_OUTCH
#define INC_OUTQ3
#define INC_OUTQ4
#define INC_OUTRG
#define INC_OUTS
#define INC_OUTS1
#define INC_OUTS2
#define INC_OUT_A
#define INC_OUT_ARRAY
#define INC_PAN
#define INC_PCHMIDI
#define INC_PCHOCT
#define INC_PHASOR
#define INC_PHASOR_K
#define INC_PLUCK
#define INC_PORT
#define INC_PORTK
#define INC_POW
#define INC_POW_A
#define INC_RAND
#define INC_RANDC
#define INC_RANDC_K
#define INC_RANDH
#define INC_RANDH_K
#define INC_RANDI
#define INC_RANDI_K
#define INC_RAND_I
#define INC_RAND_K
#define INC_RASSIGN
#define INC_RESON
#define INC_RESONK
#define INC_RESONX
#define INC_REVERB
#define INC_RMS
#define INC_RND
#define INC_RNDSEED
#define INC_ROUND
#define INC_ROUND_A
#define INC_RTCLOCK
#define INC_SAMPHOLD
#define INC_SAMPOLD_K
#define INC_SEED
#define INC_SETKSMPS
#define INC_SIGNUM
#define INC_SIGNUM_A
#define INC_SIN
#define INC_SINH
#define INC_SINH_A
#define INC_SIN_A
#define INC_SQRT
#define INC_SQRT_A
#define INC_TABLE3KT
#define INC_TABLE3KT
#define INC_TABLE3KT_A
#define INC_TABLE3KT_A
#define INC_TABLE3_A
#define INC_TABLE3_I
#define INC_TABLE3_K
#define INC_TABLECOPY
#define INC_TABLEIGPW
#define INC_TABLEIKT
#define INC_TABLEI_A
#define INC_TABLEI_I
#define INC_TABLEI_K
#define INC_TABLEMIX
#define INC_TABLENG
#define INC_TABLERA
#define INC_TABLEW
#define INC_TABLEWA
#define INC_TABLEWKT_A
#define INC_TABLEWKT_K
#define INC_TABLEW_AA
#define INC_TABLEW_KK
#define INC_TABLEW_KK
#define INC_TABLE_A
#define INC_TABLE_I
#define INC_TABLE_K
#define INC_TAN
#define INC_TANH
#define INC_TANH_A
#define INC_TAN_A
#define INC_TONE
#define INC_TONEK
#define INC_TONEX
#define INC_TRIRAND
#define INC_TRIRAND_A
#define INC_UNIRAND
#define INC_UNIRAND_A
#define INC_UPSAMP
#define INC_UPSAMPLE
#define INC_VELOC
#define INC_XADSR
#define INC_XADSR_A
#define INC_PCHMIDIB_K
#define INC_PCHMIDIB_I
#define INC_CPDMIDIB_K
#define INC_MIDIB_I
#define INC_AMPMIDI
#define INC_AFTOUCH
#define INC_MIDICTRL_I
#define INC_MIDICTRL_K
#define INC_POLYAFT_I
#define INC_POLYAFT_K
#define INC_MIDICHN
#define INC_PGMASSIN
#define INC_CHANCTRL_I
#define INC_CHANCTRL
#define INC_PCHEND_I
#define INC_PCHBEND
#define INC_MIDIIN
#define INC_PGMCHN
#define INC_CTLCHN
#define INC_MIDIARP
#define INC_CTRLSAVE
#define INC_CTRLPRINT
#define INC_CTRLPRESET
#define INC_CTRLSELECT
#define INC_CTRLPRINTPRESETS
#define INC_PVSANAL
#define INC_PVSYNTH
#define INC_PVSADSYN
#define INC_PVSASSIGN
#define INC_PVSCROSS
#define INC_PVSFREAD
#define INC_PVSMASKA
#define INC_PVSFTW
#define INC_PVSFTR
#define INC_PVSINFO
#define INC_OCTAVW
#define INC_OCTAVE_A
#define INC_SEMITONE
#define INC_SEMITONE_A
#define INC_CENT
#define INC_CENT_A
#define INC_DB
#define INC_DB_A
#define INC_LOGBASE2
#define INC_LOGBASE2_A
#define INC_DISKIN
#define INC_PRINT
#define INC_SOUNDOUT
#define INC_PVSDISP
#define INC_DISPLAY
#define INC_DISPLAY_A
#define INC_DISPFFT
#define INC_DISPFFT_A
#define INC_TEMPEST
#define INC_TEMPO
#define INC_DUMPK
#define INC_DUMPK2
#define INC_DUMPK3
#define INC_DUMPK4
#define INC_READK
#define INC_READK2
#define INC_READK3
#define INC_READK4
#define INC_READKS
#define INC_EXPRAND
#define INC_EXPRAND_A
#define INC_BEXPRAND
#define INC_BEXPRAND_A
#define INC_TRIRAND
#define INC_TRIRAND_A
#define INC_GAUSSRAND
#define INC_GAUSSRAND_A
#define INC_CAUCHYRAND
#define INC_CAUCHYRAND_A
#define INC_PCAUCHYRAND_A
#define INC_PCAUCHYRAND
#define INC_POISSONRAND
#define INC_POISSONRAND_A
#define INC_HW_CHANNELS
#define INC_WEIBULLRAND
#define INC_WEIBULLRAND_A
#define INC_BETARAND
#define INC_BETARAND_A
#define INC_FILELEN
#define INC_FILELEN_S
#define INC_FILENCHNLS
#define INC_FILENCHNLS_S
#define INC_FILEPEAK
#define INC_FILESR
#define INC_FILESR_S
#define INC_FILEVALID
#define INC_FILEVALID_S
#define INC_FILEBIT
#define INC_FILEBIT_S
#define INC_TIMEK
#define INC_TIMESR
#define INC_TIMEINSTK
#define INC_TIMEINSTS
#define INC_PRINTK
#define INC_PRINTKS
#define INC_PRINTKS_S
#define INC_PRINTS
#define INC_PRINTS_S
#define INC_PRINTKS2
#define INC_PRINTS_S
#define INC_PRINTK2
#define INC_PRINTKS2
#define INC_PEAK
#define INC_PEAKA
#define INC_INZ
#define INC_OUTZ
#define INC_SCHEDULE_ARRAY
#define INC_SCHEDULE
#define INC_SCHEDULE_N
#define INC_SCHEDULE_S
#define INC_SCHEDULE_SN
#define INC_SCHEDULEK_ARRAY
#define INC_SCHEDULEK
#define INC_SCHEDULEK_N
#define INC_SCHEDULEK_S
#define INC_SCHEDULEK_SN
#define INC_SCHEDWHEN
#define INC_LFO
#define INC_LFOA
#define INC_SCHEDKWHEN
#define INC_SCHEDKWHEN_S
#define INC_TRIGSEQ
#define INC_OSCILS
#define INC_LPHASOR
#define INC_TABLEXKT
#define INC_REVERB2
#define INC_VDELAY
#define INC_VDELAY3
#define INC_VDELAYXWQ 
#define INC_VDELAYXWS
#define INC_VDELAYX
#define INC_VDELAYXS
#define INC_VDELAYXQ
#define INC_MULTITAP
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_
#define INC_




