import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import importPlugin from "eslint-plugin-import-x";
import nodePlugin from "eslint-plugin-n";
import promise from "eslint-plugin-promise";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

// Keep the existing Unicorn checks; adopting new style rules is a separate change.
const unicornRules = [
  "unicorn/catch-error-name",
  "unicorn/consistent-empty-array-spread",
  "unicorn/consistent-existence-index-check",
  "unicorn/consistent-function-scoping",
  "unicorn/empty-brace-spaces",
  "unicorn/error-message",
  "unicorn/escape-case",
  "unicorn/expiring-todo-comments",
  "unicorn/explicit-length-check",
  "unicorn/filename-case",
  "unicorn/import-style",
  "unicorn/new-for-builtins",
  "unicorn/no-anonymous-default-export",
  "unicorn/no-array-method-this-argument",
  "unicorn/prefer-single-call",
  "unicorn/no-await-expression-member",
  "unicorn/no-await-in-promise-methods",
  "unicorn/no-console-spaces",
  "unicorn/no-document-cookie",
  "unicorn/no-empty-file",
  "unicorn/no-for-loop",
  "unicorn/prefer-unicode-code-point-escapes",
  "unicorn/no-instanceof-builtins",
  "unicorn/no-invalid-fetch-options",
  "unicorn/no-invalid-remove-event-listener",
  "unicorn/no-unnecessary-slice-end",
  "unicorn/no-lonely-if",
  "unicorn/no-magic-array-flat-depth",
  "unicorn/no-negated-condition",
  "unicorn/no-negation-in-equality-check",
  "unicorn/no-new-array",
  "unicorn/no-new-buffer",
  "unicorn/no-object-as-default-parameter",
  "unicorn/no-process-exit",
  "unicorn/no-single-promise-in-promise-methods",
  "unicorn/no-static-only-class",
  "unicorn/no-thenable",
  "unicorn/no-this-assignment",
  "unicorn/no-typeof-undefined",
  "unicorn/no-unnecessary-await",
  "unicorn/no-unnecessary-polyfills",
  "unicorn/no-unreadable-array-destructuring",
  "unicorn/no-unreadable-iife",
  "unicorn/no-useless-fallback-in-spread",
  "unicorn/no-useless-length-check",
  "unicorn/no-useless-promise-resolve-reject",
  "unicorn/no-useless-spread",
  "unicorn/no-useless-switch-case",
  "unicorn/no-zero-fractions",
  "unicorn/number-literal-case",
  "unicorn/prefer-add-event-listener",
  "unicorn/prefer-array-find",
  "unicorn/prefer-array-flat",
  "unicorn/prefer-array-flat-map",
  "unicorn/prefer-array-index-of",
  "unicorn/prefer-array-some",
  "unicorn/prefer-blob-reading-methods",
  "unicorn/prefer-code-point",
  "unicorn/prefer-date-now",
  "unicorn/prefer-default-parameters",
  "unicorn/prefer-dom-node-append",
  "unicorn/dom-node-dataset",
  "unicorn/prefer-dom-node-remove",
  "unicorn/prefer-dom-node-text-content",
  "unicorn/prefer-event-target",
  "unicorn/prefer-export-from",
  "unicorn/prefer-global-this",
  "unicorn/prefer-includes",
  "unicorn/prefer-keyboard-event-key",
  "unicorn/prefer-logical-operator-over-ternary",
  "unicorn/prefer-math-min-max",
  "unicorn/prefer-math-trunc",
  "unicorn/prefer-modern-dom-apis",
  "unicorn/prefer-modern-math-apis",
  "unicorn/prefer-module",
  "unicorn/prefer-native-coercion-functions",
  "unicorn/prefer-negative-index",
  "unicorn/prefer-node-protocol",
  "unicorn/prefer-number-properties",
  "unicorn/prefer-object-from-entries",
  "unicorn/prefer-prototype-methods",
  "unicorn/prefer-query-selector",
  "unicorn/prefer-reflect-apply",
  "unicorn/prefer-regexp-test",
  "unicorn/prefer-set-has",
  "unicorn/prefer-set-size",
  "unicorn/prefer-spread",
  "unicorn/prefer-string-raw",
  "unicorn/prefer-string-replace-all",
  "unicorn/prefer-string-slice",
  "unicorn/prefer-string-starts-ends-with",
  "unicorn/prefer-string-trim-start-end",
  "unicorn/prefer-structured-clone",
  "unicorn/prefer-switch",
  "unicorn/prefer-ternary",
  "unicorn/prefer-top-level-await",
  "unicorn/prefer-type-error",
  "unicorn/relative-url-style",
  "unicorn/require-array-join-separator",
  "unicorn/require-number-to-fixed-digits-argument",
  "unicorn/switch-case-braces",
  "unicorn/template-indent",
  "unicorn/text-encoding-identifier-case",
  "unicorn/throw-new-error",
];

export default [
  { ignores: ["**/coverage", "**/dist", "**/node_modules", "**/*.config.js", "**/logger*.js"] },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        __PROD__: "readonly",
        goog: "readonly",
        Zlib: "writable",
      },
    },
    plugins: { "import-x": importPlugin, n: nodePlugin, promise, unicorn },
    rules: {
      ...js.configs.recommended.rules,
      // Retain the extra checks used by this project.
      "no-var": "warn",
      "object-shorthand": ["warn", "properties"],
      "accessor-pairs": [
        "error",
        {
          setWithoutGet: true,
          enforceForClassMembers: true,
        },
      ],
      "array-callback-return": [
        "error",
        {
          allowImplicit: false,
          checkForEach: false,
        },
      ],
      camelcase: [
        "error",
        {
          allow: ["^UNSAFE_"],
          properties: "never",
          ignoreGlobals: true,
        },
      ],
      "default-case-last": "error",
      eqeqeq: [
        "error",
        "always",
        {
          null: "ignore",
        },
      ],
      "lines-between-class-members": [
        "error",
        "always",
        {
          exceptAfterSingleLine: true,
        },
      ],
      "new-cap": [
        "error",
        {
          newIsCap: true,
          capIsNew: false,
          properties: true,
        },
      ],
      "no-array-constructor": "error",
      "no-caller": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-labels": [
        "error",
        {
          allowLoop: false,
          allowSwitch: false,
        },
      ],
      "no-lone-blocks": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-symbol": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-return-assign": ["error", "except-parens"],
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": [
        "error",
        {
          defaultAssignment: false,
        },
      ],
      "no-unreachable-loop": "error",
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTernary: true,
          allowTaggedTemplates: true,
        },
      ],
      "no-use-before-define": [
        "error",
        {
          functions: false,
          classes: false,
          variables: false,
        },
      ],
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "one-var": [
        "error",
        {
          initialized: "never",
        },
      ],
      "prefer-const": [
        "error",
        {
          destructuring: "all",
        },
      ],
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": [
        "error",
        {
          disallowRedundantWrapping: true,
        },
      ],
      "spaced-comment": [
        "error",
        "always",
        {
          line: {
            markers: ["*package", "!", "/", ",", "="],
          },
          block: {
            balanced: true,
            markers: ["*package", "!", ",", ":", "::", "flow-include"],
            exceptions: ["*"],
          },
        },
      ],
      "symbol-description": "error",
      "unicode-bom": ["error", "never"],
      yoda: ["error", "never"],
      "import-x/export": "error",
      "import-x/first": "error",
      "import-x/no-absolute-path": [
        "error",
        {
          esmodule: true,
          commonjs: true,
          amd: false,
        },
      ],
      "import-x/no-duplicates": "error",
      "import-x/no-named-default": "error",
      "import-x/no-webpack-loader-syntax": "error",
      "n/handle-callback-err": ["error", "^(err|error)$"],
      "n/no-callback-literal": "error",
      "n/no-deprecated-api": "error",
      "n/no-exports-assign": "error",
      "n/no-new-require": "error",
      "n/no-path-concat": "error",
      "n/process-exit-as-throw": "error",
      "promise/param-names": "error",
      "no-unused-vars": [
        "error",
        {
          args: "none",
          caughtErrors: "none",
          ignoreRestSiblings: true,
          vars: "all",
        },
      ],
      "no-empty": [
        "error",
        {
          allowEmptyCatch: true,
        },
      ],
      "no-constant-condition": [
        "error",
        {
          checkLoops: false,
        },
      ],
      "no-redeclare": [
        "error",
        {
          builtinGlobals: false,
        },
      ],
      "no-self-assign": [
        "error",
        {
          props: true,
        },
      ],
      "use-isnan": [
        "error",
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      "valid-typeof": [
        "error",
        {
          requireStringLiterals: true,
        },
      ],
      ...Object.fromEntries(unicornRules.map((rule) => [rule, "error"])),
      ...prettier.rules,
      "dot-notation": "off",
    },
  },
];
