import standard from "eslint-config-standard";
import prettier from "eslint-config-prettier";
import importPlugin from "eslint-plugin-import";
import nodePlugin from "eslint-plugin-n";
import promise from "eslint-plugin-promise";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";

// Keep the existing Unicorn checks; adopting new style rules is a separate change.
const unicornRules = [
  "unicorn/catch-error-name",
  "unicorn/consistent-empty-array-spread",
  "unicorn/consistent-existence-index-check",
  "unicorn/consistent-function-scoping",
  "unicorn/empty-brace-spaces",
  "unicorn/error-message",
  "unicorn/escape-case",
  "unicorn/expiring-todo-comments",
  "unicorn/explicit-length-check",
  "unicorn/filename-case",
  "unicorn/import-style",
  "unicorn/new-for-builtins",
  "unicorn/no-anonymous-default-export",
  "unicorn/no-array-method-this-argument",
  "unicorn/prefer-single-call",
  "unicorn/no-await-expression-member",
  "unicorn/no-await-in-promise-methods",
  "unicorn/no-console-spaces",
  "unicorn/no-document-cookie",
  "unicorn/no-empty-file",
  "unicorn/no-for-loop",
  "unicorn/prefer-unicode-code-point-escapes",
  "unicorn/no-instanceof-builtins",
  "unicorn/no-invalid-fetch-options",
  "unicorn/no-invalid-remove-event-listener",
  "unicorn/no-unnecessary-slice-end",
  "unicorn/no-lonely-if",
  "unicorn/no-magic-array-flat-depth",
  "unicorn/no-negated-condition",
  "unicorn/no-negation-in-equality-check",
  "unicorn/no-new-array",
  "unicorn/no-new-buffer",
  "unicorn/no-object-as-default-parameter",
  "unicorn/no-process-exit",
  "unicorn/no-single-promise-in-promise-methods",
  "unicorn/no-static-only-class",
  "unicorn/no-thenable",
  "unicorn/no-this-assignment",
  "unicorn/no-typeof-undefined",
  "unicorn/no-unnecessary-await",
  "unicorn/no-unnecessary-polyfills",
  "unicorn/no-unreadable-array-destructuring",
  "unicorn/no-unreadable-iife",
  "unicorn/no-useless-fallback-in-spread",
  "unicorn/no-useless-length-check",
  "unicorn/no-useless-promise-resolve-reject",
  "unicorn/no-useless-spread",
  "unicorn/no-useless-switch-case",
  "unicorn/no-zero-fractions",
  "unicorn/number-literal-case",
  "unicorn/prefer-add-event-listener",
  "unicorn/prefer-array-find",
  "unicorn/prefer-array-flat",
  "unicorn/prefer-array-flat-map",
  "unicorn/prefer-array-index-of",
  "unicorn/prefer-array-some",
  "unicorn/prefer-blob-reading-methods",
  "unicorn/prefer-code-point",
  "unicorn/prefer-date-now",
  "unicorn/prefer-default-parameters",
  "unicorn/prefer-dom-node-append",
  "unicorn/dom-node-dataset",
  "unicorn/prefer-dom-node-remove",
  "unicorn/prefer-dom-node-text-content",
  "unicorn/prefer-event-target",
  "unicorn/prefer-export-from",
  "unicorn/prefer-global-this",
  "unicorn/prefer-includes",
  "unicorn/prefer-keyboard-event-key",
  "unicorn/prefer-logical-operator-over-ternary",
  "unicorn/prefer-math-min-max",
  "unicorn/prefer-math-trunc",
  "unicorn/prefer-modern-dom-apis",
  "unicorn/prefer-modern-math-apis",
  "unicorn/prefer-module",
  "unicorn/prefer-native-coercion-functions",
  "unicorn/prefer-negative-index",
  "unicorn/prefer-node-protocol",
  "unicorn/prefer-number-properties",
  "unicorn/prefer-object-from-entries",
  "unicorn/prefer-prototype-methods",
  "unicorn/prefer-query-selector",
  "unicorn/prefer-reflect-apply",
  "unicorn/prefer-regexp-test",
  "unicorn/prefer-set-has",
  "unicorn/prefer-set-size",
  "unicorn/prefer-spread",
  "unicorn/prefer-string-raw",
  "unicorn/prefer-string-replace-all",
  "unicorn/prefer-string-slice",
  "unicorn/prefer-string-starts-ends-with",
  "unicorn/prefer-string-trim-start-end",
  "unicorn/prefer-structured-clone",
  "unicorn/prefer-switch",
  "unicorn/prefer-ternary",
  "unicorn/prefer-top-level-await",
  "unicorn/prefer-type-error",
  "unicorn/relative-url-style",
  "unicorn/require-array-join-separator",
  "unicorn/require-number-to-fixed-digits-argument",
  "unicorn/switch-case-braces",
  "unicorn/template-indent",
  "unicorn/text-encoding-identifier-case",
  "unicorn/throw-new-error",
];

export default [
  { ignores: ["**/coverage", "**/dist", "**/node_modules", "**/*.config.js", "**/logger*.js"] },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        __PROD__: "readonly",
        goog: "readonly",
        Zlib: "writable",
      },
    },
    plugins: { import: importPlugin, n: nodePlugin, promise, unicorn },
    rules: {
      ...standard.rules,
      ...Object.fromEntries(unicornRules.map((rule) => [rule, "error"])),
      ...prettier.rules,
      "dot-notation": "off",
    },
  },
];
