if(NOT LIBSAMPLERATE_LIBRARY)
  find_library(LIBSAMPLERATE_LIBRARY NAMES samplerate libsamplerate-0 HINTS "${LIBSAMPLERATE_LIBRARY_DIRECTORY}")
endif()

if(NOT LIBSAMPLERATE_INCLUDE_DIRECTORY)
  find_path(LIBSAMPLERATE_INCLUDE_DIRECTORY NAMES "samplerate.h")
endif()
