
check_c_compiler_flag(-ftree-vectorize HAS_TREE_VECTORIZE)
check_cxx_compiler_flag(-ftree-vectorize HAS_CXX_TREE_VECTORIZE)
if (HAS_TREE_VECTORISE)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-ftree-vectorize>")
endif()
if (HAS_CXX_TREE_VECTORISE)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-ftree-vectorize>")
endif()


check_c_compiler_flag(-ffast-math HAS_FAST_MATH)
check_cxx_compiler_flag(-ffast-math HAS_CXX_FAST_MATH)
if (HAS_FAST_MATH AND NOT MINGW)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-ffast-math>")
endif()
if (HAS_CXX_FAST_MATH AND NOT MINGW)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-ffast-math>")
endif()

check_c_compiler_flag(-mfpmath=sse HAS_FPMATH_SSE)
check_cxx_compiler_flag(-mfpmath=sse HAS_CXX_FPMATH_SSE)
if (HAS_FPMATH_SSE)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-mfpmath=sse>")
endif()
if (HAS_CXX_FPMATH_SSE)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-mfpmath=sse>")
endif()

check_c_compiler_flag(-msse2 HAS_SSE2)
check_cxx_compiler_flag(-msse2 HAS_CXX_SSE2)
if (HAS_SSE2)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-msse2>")
endif()
if (HAS_CXX_SSE2)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-msse2>")
endif()

check_c_compiler_flag(-fomit-frame-pointer HAS_OMIT_FRAME_POINTER)
check_cxx_compiler_flag(-fomit-frame-pointer HAS_CXX_OMIT_FRAME_POINTER)
if (HAS_OMIT_FRAME_POINTER)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>")
endif()
if (HAS_CXX_OMIT_FRAME_POINTER)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>")
endif()

check_c_compiler_flag(-fvisibility=hidden HAS_VISIBILITY_HIDDEN)
check_cxx_compiler_flag(-fvisibility=hidden HAS_CXX_VISIBILITY_HIDDEN)
if (HAS_VISIBILITY_HIDDEN)
    add_compile_options("$<$<COMPILE_LANGUAGE:C>:-fvisibility=hidden>")
endif()
if (HAS_CXX_VISIBILITY_HIDDEN)
    add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-fvisibility=hidden>")
endif()
