if (NOT IOS)
    try_add_compile_option("-ftree-vectorize")
    try_add_compile_option("-ffast-math")
    if(NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        try_add_compile_option("-mfpmath=sse")
    endif()
    try_add_compile_option("-msse2")
    try_add_compile_option("-fomit-frame-pointer")
endif()
