<CsTest>
description = "SoundFont playback rejects invalid instrument handles and excess matching zones"
[expect]
exit = "nonzero"
stderr = ["invalid soundfont", "instrument out of range", "too many matching sample zones"]
</CsTest>
<CsoundSynthesizer>
<CsOptions>
-n -d -m0
</CsOptions>
<CsFileB filename="sfinstr-init-errors.sf2">
UklGRtQHAABzZmJrTElTVDwAAABJTkZPaWZpbAQAAAACAAEAaXNuZwgAAABFTVU4MDAwAElOQU0U
AAAARW52ZWxvcGUgcmVncmVzc2lvbgBMSVNUaAIAAHNkdGFzbXBsXAIAAAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAABMSVNUFAUAAHBkdGFwaGRyfAEAAFByZXNldCAwAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAUHJlc2V0IDEAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAA
AABQcmVzZXQgMgAAAAAAAAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAFByZXNldCAzAAAAAAAAAAAA
AAAAAwAAAAMAAAAAAAAAAAAAAAAAUHJlc2V0IDQAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAA
AABQcmVzZXQgNQAAAAAAAAAAAAAAAAUAAAAFAAAAAAAAAAAAAAAAAFByZXNldCA2AAAAAAAAAAAA
AAAABgAAAAYAAAAAAAAAAAAAAAAAUHJlc2V0IDcAAAAAAAAAAAAAAAAHAAAABwAAAAAAAAAAAAAA
AABQcmVzZXQgOAAAAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAEVPUAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAkAAAAAAAAAAAAAAAAAcGJhZygAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAA
BwAAAAgAAAAJAAAAcG1vZAoAAAAAAAAAAAAAAAAAcGdlbigAAAApAAAAKQABACkAAgApAAMAKQAE
ACkABQApAAYAKQAHACkACAAAAAAAaW5zdNwAAABJbnN0cnVtZW50IDAAAAAAAAAAAAAASW5zdHJ1
bWVudCAxAAAAAAAAAAABAEluc3RydW1lbnQgMgAAAAAAAAAAAgBJbnN0cnVtZW50IDMAAAAAAAAA
AAMASW5zdHJ1bWVudCA0AAAAAAAAAAAEAEluc3RydW1lbnQgNQAAAAAAAAAABQBJbnN0cnVtZW50
IDYAAAAAAAAAAAcASW5zdHJ1bWVudCA3AAAAAAAAAAAJAEluc3RydW1lbnQgOAAAAAAAAAAAEwBF
T0kAAAAAAAAAAAAAAAAAAAAAAB4AaWJhZ3wAAAAAAAAABQAAAAoAAAAOAAAAEwAAABUAAAAYAAAA
GgAAAB0AAAAiAAAAJAAAACYAAAAoAAAAKgAAACwAAAAuAAAAMAAAADIAAAA0AAAANgAAADgAAAA6
AAAAPAAAAD4AAABAAAAAQgAAAEQAAABGAAAASAAAAEoAAABMAAAAaW1vZAoAAAAAAAAAAAAAAAAA
aWdlbjQBAAAiAKD2JACg9iUAyAA2AAEANQAAACIAoPYkAKD2JQDIADYAAAA1AAAAIgCg9iQAoPY2
AAEANQAAACIAoPYkAKD2JQA4/zYAAQA1AAAANgABADUAAAAiAKD2JACg9iUAyAA2AAEANQAAACIA
8PEkAFD7JQCQASIAoPYkAKD2JQDIADYAAQA1AAAANgABADUAAAA2AAEANQAAADYAAQA1AAAANgAB
ADUAAAA2AAEANQAAADYAAQA1AAAANgABADUAAAA2AAEANQAAADYAAQA1AAAANgABADUAAAA2AAEA
NQAAADYAAQA1AAAANgABADUAAAA2AAEANQAAADYAAQA1AAAANgABADUAAAA2AAEANQAAADYAAQA1
AAAANgABADUAAAA2AAEANQAAADYAAQA1AAAAAAAAAHNoZHJcAAAAQ29uc3RhbnQAAAAAAAAAAAAA
AAAAAAAAAAEAAAgAAAD4AAAAAAQAADwAAAABAEVPUwAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA
AQAAAAEAAAAEAAAAAAAAAQA=
</CsFileB>
<CsInstruments>
sr=1024
ksmps=32
nchnls=1
giFont sfload "sfinstr-init-errors.sf2"
sfpassign 0, giFont, 0
instr 1
 aL,aR sfinstr 100,60,1,0,p4,p5
endin
instr 2
 aOut sfinstrm 100,60,1,0,p4,p5
endin
instr 3
 aL,aR sfinstr3 100,60,1,0,p4,p5
endin
instr 4
 aOut sfinstr3m 100,60,1,0,p4,p5
endin
instr 5
 aL,aR sfplay 100,60,1,0,p4
endin
instr 6
 aOut sfplaym 100,60,1,0,p4
endin
instr 7
 aL,aR sfplay3 100,60,1,0,p4
endin
instr 8
 aOut sfplay3m 100,60,1,0,p4
endin
instr 9
 aL,aR sflooper 100,60,1,1,p4,8,64,0
endin
</CsInstruments>
<CsScore>
i 1 0 .01 8 0
i 2 0 .01 8 0
i 3 0 .01 8 0
i 4 0 .01 8 0
i 5 0 .01 8 0
i 6 0 .01 8 0
i 7 0 .01 8 0
i 8 0 .01 8 0
i 9 0 .01 8 0
i 1 0 .01 -1 0
i 1 0 .01 9 0
i 1 0 .01 0 -1
i 1 0 .01 0 1
i 2 0 .01 -1 0
i 2 0 .01 9 0
i 2 0 .01 0 -1
i 2 0 .01 0 1
i 3 0 .01 -1 0
i 3 0 .01 9 0
i 3 0 .01 0 -1
i 3 0 .01 0 1
i 4 0 .01 -1 0
i 4 0 .01 9 0
i 4 0 .01 0 -1
i 4 0 .01 0 1
</CsScore>
</CsoundSynthesizer>
