<CsTest>
description = "SoundFont preset assignment and looping reject out-of-range handles"
[expect]
exit = "nonzero"
stderr = ["sfpassign: preset range out of bounds", "sflooper: preset number out of range"]
</CsTest>
<CsoundSynthesizer>
<CsOptions>
-n -d -m0
</CsOptions>
<CsFileB filename="sfpassign-bounds.sf2">
UklGRrACAABzZmJrTElTVCYAAABJTkZPaWZpbAQAAAACAAEASU5BTQ4AAABQcmVzZXQgYm91bmRz
AExJU1ToAAAAc2R0YXNtcGzcAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAExJU1SGAQAAcGR0YXBoZHJyAAAARmlyc3QAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABTZWNvbmQAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAEVPUAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAcGJhZwwAAAAAAAAAAQAAAAIAAABwbW9k
CgAAAAAAAAAAAAAAAABwZ2VuDAAAACkAAAApAAAAAAAAAGluc3QsAAAAQ29uc3RhbnQAAAAAAAAA
AAAAAAAAAEVPSQAAAAAAAAAAAAAAAAAAAAAAAQBpYmFnCAAAAAAAAAACAAAAaW1vZAoAAAAAAAAA
AAAAAAAAaWdlbgwAAAA2AAEANQAAAAAAAABzaGRyXAAAAENvbnN0YW50AAAAAAAAAAAAAAAAAAAA
AEAAAAAIAAAAOAAAAAAEAAA8AAAAAQBFT1MAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAA
AAAABAAAPAAAAAEA
</CsFileB>
<CsInstruments>
sr = 1024
ksmps = 8
nchnls = 1
0dbfs = 1
giFont sfload "sfpassign-bounds.sf2"
instr 1
  sfpassign p4, giFont, 1
endin
instr 2
  aL, aR sflooper 100, 60, 1, 1, p4, 8, 56, 0
endin
</CsInstruments>
<CsScore>
i 1 0 .01 -1
i 1 0 .01 16383
i 1 0 .01 16384
i 1 0 .01 1e30
i 2 0 .01 -1
i 2 0 .01 16384
</CsScore>
</CsoundSynthesizer>
