<CsTest>
description = "sfpassign accepts assignments ending at the final preset handle"
[expect]
exit = 0
</CsTest>
<CsoundSynthesizer>
<CsOptions>
-n -d -m0
</CsOptions>
<CsFileB filename="sfpassign-endpoint.sf2">
UklGRrACAABzZmJrTElTVCYAAABJTkZPaWZpbAQAAAACAAEASU5BTQ4AAABQcmVzZXQgYm91bmRz
AExJU1ToAAAAc2R0YXNtcGzcAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQ
ABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAA
EAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAExJU1SGAQAAcGR0YXBoZHJyAAAARmlyc3QAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABTZWNvbmQAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAEVPUAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAcGJhZwwAAAAAAAAAAQAAAAIAAABwbW9k
CgAAAAAAAAAAAAAAAABwZ2VuDAAAACkAAAApAAAAAAAAAGluc3QsAAAAQ29uc3RhbnQAAAAAAAAA
AAAAAAAAAEVPSQAAAAAAAAAAAAAAAAAAAAAAAQBpYmFnCAAAAAAAAAACAAAAaW1vZAoAAAAAAAAA
AAAAAAAAaWdlbgwAAAA2AAEANQAAAAAAAABzaGRyXAAAAENvbnN0YW50AAAAAAAAAAAAAAAAAAAA
AEAAAAAIAAAAOAAAAAAEAAA8AAAAAQBFT1MAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAA
AAAABAAAPAAAAAEA
</CsFileB>
<CsInstruments>
sr = 1024
ksmps = 8
nchnls = 1
0dbfs = 1
giFont sfload "sfpassign-endpoint.sf2"
; Both presets use the same constant sample.
sfpassign 0, giFont, 1
sfpassign 16382, giFont, 1
instr 1
  aLow sfplaym 100, 60, 1, 0, 1, 0, 16
  aHigh sfplaym 100, 60, 1, 0, 16383, 0, 16
  kLevel max_k aLow, 1, 1
  kError max_k abs(aHigh-aLow), 1, 1
  if kLevel <= 0 || kError > .000001 then
    exitnowk -1
  endif
endin
</CsInstruments>
<CsScore>
i 1 0 .05
</CsScore>
</CsoundSynthesizer>
