name: Csound WASM command-line tests

on:
  workflow_run:
    workflows: ["csound_wasm"]
    types: [completed]

jobs:
  commandline-tests:
    name: CSD tests with Wasmtime
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo true
