name: docker_builds

on:
#  pull_request:
#    branches:
#      - develop
  workflow_dispatch:

jobs:
  build-and-push-android-image:
    name: Android
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t csound-android:${{ env.VERSION }} platform/android
          docker save csound-android:${{ env.VERSION }} > csound-android-${{ env.VERSION }}.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: csound-android-${{ env.VERSION }}
          path: csound-android-${{ env.VERSION }}.tar

      - name: Update workflow_run_id
        if: ${{ success() }}
        run: |
          gh variable set ANDROID_WORKFLOW_RUN_ID --body ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
