name: Lint Tidy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install cmake libsndfile1-dev libasound2-dev libjack-dev portaudio19-dev libportmidi-dev libpulse-dev swig liblua5.1-0-dev default-jdk libfltk1.1-dev libfluidsynth-dev liblo-dev fluid ladspa-sdk libpng-dev dssi-dev libstk0-dev libgmm++-dev bison flex libportsmf-dev libeigen3-dev libgtest-dev
      - name: Configure build
        run: mkdir build && cd build && cmake .. -DBUILD_STATIC_LIBRARY=1 -DUSE_MP3=0
      - name: Tidy
        run: cd build && make tidy
